export const ShopActionTypes = {

    FETCH_COLLECTIONS_START: 'FETCH_COLLECTION_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_ERROR: 'FETCH_COLLECTIONS_ERROR'

    //SET_COLLECTIONS: 'SET_COLLECTIONS'
}